- hosts: localhost
  vars:
    source_key: "./.ssh/id_ed25519_github"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519_github"
    i3_tags: ["install", "core", "i3"]
    picom_dir: "{{ lookup('env', 'HOME') }}"
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
  tasks:
    - include: tasks/git-setup.yml
    - include: tasks/core-setup.yml
    - include: tasks/i3-setup.yml
    - include: tasks/zsh-setup.yml
    - include: tasks/nvim-setup.yml
    - include: tasks/brave.yml
    - include: tasks/dotfiles.yml
    - include: tasks/productivity-tools.yml
