- name: Installing stow
  apt: name=stow
  tags:
    - install
    - dotfiles
    - stow
  become: true
- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'https://github.com/hampusek/.dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: no
    update: yes
    version: master
  tags:
    - install
    - dotfiles
    - stow
- name: Stow dotfiles
  shell: cd ~/.dotfiles && chmod +x ~/.dotfiles/ubuntu && \
    chmod +x ~/.dotfiles/install && ./ubuntu
  tags:
    - install
    - dotfiles
    - stow
