- name: Install System Packages 3 (the rest)
  become: true
  apt:
    name: [ "i3", "dconf-editor", "pavucontrol", "ubuntu-mate-desktop" ]
  tags:
    - install
    - core

- name: dconf i3
  shell: dconf write /org/mate/desktop/session/required-components/windowmanager "'i3'"
  tags:
    - install
    - core

- name: dconf i3
  shell: dconf write /org/mate/desktop/background/show-desktop-icons "false"
  tags:
    - install
    - corea
