- name: Remove neovim
  shell: rm -rf "{{ lookup('env', 'HOME') }}/neovim"
  tags:
    - install
    - neovim
- name: Clone Neovim
  ansible.builtin.git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: "{{ lookup('env', 'HOME') }}/neovim"
  tags:
    - install
    - neovim
- name: Build neovim
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make CMAKE_BUILD_TYPE=Release"
  tags:
    - install
    - neovim
- name: Install neovim
  become: true
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make install"
  tags:
    - install
    - neovim

- name: install python packages to neovim python venv
  pip:
    name:
      - pynvim
      - pyright
      - debugpy
    executable: "pip3"
  tags:
    - install
    - neovim
    - pynvim

